Repository PlaceOS/rest-api, pull requests merged in 2021-11, with the labels that each got.

#166 fix: settings support view
  spec/controllers/settings_spec.cr
Labels: type: bug

#217 feat(api): forward `user_id` for module executes
  src/placeos-rest-api/controllers/modules.cr
  src/placeos-rest-api/controllers/systems.cr
  src/placeos-rest-api/controllers/webhook.cr
  src/placeos-rest-api/controllers/zones.cr
  src/placeos-rest-api/websocket/session.cr
Labels: type: enhancement

#220 refactor: mqtt permissions check
  spec/controllers/root_spec.cr
  src/placeos-rest-api/controllers/application.cr
  src/placeos-rest-api/controllers/root.cr
Labels: type: refactor

#219 feat: add helper methods for authenticating MQTT websocket access
  shard.lock
  spec/controllers/mqtt_spec.cr
  spec/controllers/root_spec.cr
  src/placeos-rest-api/controllers/application.cr
  src/placeos-rest-api/controllers/mqtt.cr
  src/placeos-rest-api/controllers/root.cr
  src/placeos-rest-api/utilities/scopes.cr
Labels: focus: backend, product: placeos
