Repository PlaceOS/rest-api, pull requests merged in 2021-12, with the labels that each got.

#221 ci: use `search-ingest`
  Dockerfile
  docker-compose.yml
  shard.lock
  spec/controllers/brokers_spec.cr
  spec/controllers/drivers_spec.cr
  spec/controllers/modules_spec.cr
  spec/controllers/repositories_spec.cr
  spec/controllers/systems_spec.cr
  spec/controllers/triggers_spec.cr
  spec/controllers/users_spec.cr
  spec/controllers/zones_spec.cr
  spec/helper.cr
  spec/scope_helper.cr
Labels: focus: devops, type: maintenance

#222 feat(assets): add controller & spec
  Dockerfile
  shard.lock
  shard.yml
  spec/controllers/asset_instances_spec.cr
  spec/controllers/asset_spec.cr
  spec/helper.cr
  src/placeos-rest-api/controllers/asset_instances.cr
  src/placeos-rest-api/controllers/assets.cr
Labels: type: new feature

#223 fix(mqtt controller): deny flag is also a read flag
  src/placeos-rest-api/controllers/mqtt.cr
Labels: focus: backend, type: bug
