Repository PlaceOS/rest-api, pull requests merged in 2022-01, with the labels that each got.

#224 feat(users controller): add support for user model soft delete
  shard.lock
  src/placeos-rest-api/controllers/users.cr
Labels: focus: backend, product: placeos, priority: medium

#225 chore: remove `Enumerable#tally_by` implementation
  src/placeos-rest-api/controllers/systems.cr
Labels: type: maintenance

#226 test: run pending spec
  shard.lock
  spec/controllers/brokers_spec.cr
  spec/controllers/drivers_spec.cr
  spec/controllers/modules_spec.cr
  spec/controllers/mqtt_spec.cr
  spec/controllers/settings_spec.cr
  spec/controllers/systems_spec.cr
  spec/websocket/session_spec.cr
  src/placeos-rest-api/controllers/modules.cr
Labels: type: maintenance

#227 fix: swallow channel errors in single document changefeeds
  shard.lock
  spec/controllers/drivers_spec.cr
  spec/controllers/settings_spec.cr
  spec/websocket/session_spec.cr
  src/placeos-rest-api/controllers/drivers.cr
  src/placeos-rest-api/controllers/repositories.cr
  src/placeos-rest-api/utilities/changefeeds.cr
Labels: type: bug, type: refactor

#228 feat(controllers:root): add `/platform` to render platform metadata
  Dockerfile
  spec/controllers/asset_spec.cr
  spec/controllers/modules_spec.cr
  spec/controllers/root_spec.cr
  spec/controllers/settings_spec.cr
  spec/controllers/system-triggers_spec.cr
  spec/controllers/systems_spec.cr
  spec/controllers/triggers_spec.cr
  src/constants.cr
  src/placeos-rest-api/controllers/root.cr
Labels: type: new feature
