Repository PlaceOS/rest-api, pull requests merged in 2022-03, with the labels that each got.

#238 feat: add a flux query route
  src/constants.cr
  src/placeos-rest-api/controllers/flux.cr
Labels: focus: backend, priority: critical, product: placeos

#239 refactor(api): `put_redirect` to prevent manual update redirect
  src/placeos-rest-api/controllers/api_keys.cr
  src/placeos-rest-api/controllers/application.cr
  src/placeos-rest-api/controllers/authentications.cr
  src/placeos-rest-api/controllers/brokers.cr
  src/placeos-rest-api/controllers/domains.cr
  src/placeos-rest-api/controllers/drivers.cr
  src/placeos-rest-api/controllers/edges.cr
  src/placeos-rest-api/controllers/metadata.cr
  src/placeos-rest-api/controllers/modules.cr
  src/placeos-rest-api/controllers/oauth_applications.cr
  src/placeos-rest-api/controllers/repositories.cr
  src/placeos-rest-api/controllers/schema.cr
  src/placeos-rest-api/controllers/settings.cr
  src/placeos-rest-api/controllers/system-triggers.cr
  src/placeos-rest-api/controllers/systems.cr
  src/placeos-rest-api/controllers/triggers.cr
  src/placeos-rest-api/controllers/users.cr
  src/placeos-rest-api/controllers/zones.cr
  src/placeos-rest-api/utilities/put_redirect.cr
Labels: type: refactor

#240 fix(systems execute): fix response using driver status codes
  src/placeos-rest-api/controllers/systems.cr
Labels: focus: backend, priority: critical, product: placeos, squad: core, type: bug

#242 fix(controllers/modules): extract status from exec response
  shard.lock
  src/placeos-rest-api/controllers/modules.cr
  src/placeos-rest-api/controllers/zones.cr
Labels: type: bug

#241 ci: set original commit for TODO purposes
  .github/workflows/ci.yml
Labels: focus: devops, type: maintenance

#254 build: bump `placeos-models`
  .github/workflows/ci.yml
  shard.lock
  shard.override.yml
  shard.yml
  src/placeos-rest-api/controllers/application.cr
Labels: type: maintenance

#256 feat: set modifier for metadata and settings
  shard.lock
  src/placeos-rest-api/controllers/metadata.cr
  src/placeos-rest-api/controllers/settings.cr
Labels: type: new feature

#258 feat(metadata#history): add `/metadata/:parent_id/history`
  docker-compose.yml
  shard.lock
  spec/controllers/asset_instances_spec.cr
  spec/controllers/asset_spec.cr
  spec/controllers/brokers_spec.cr
  spec/controllers/drivers_spec.cr
  spec/controllers/metadata_spec.cr
  spec/controllers/modules_spec.cr
  spec/controllers/repositories_spec.cr
  spec/controllers/root_spec.cr
  spec/controllers/settings_spec.cr
  spec/controllers/systems_spec.cr
  spec/controllers/triggers_spec.cr
  spec/controllers/users_spec.cr
  spec/controllers/zones_spec.cr
  spec/helper.cr
  spec/scope_helper.cr
  spec/websocket/session_spec.cr
  src/placeos-rest-api/controllers/metadata.cr
  src/placeos-rest-api/controllers/settings.cr
Labels: type: enhancement, type: new feature

#259 refactor(controllers): remove `find_<model>` from `current_<model>`
  src/placeos-rest-api/controllers/api_keys.cr
  src/placeos-rest-api/controllers/asset_instances.cr
  src/placeos-rest-api/controllers/assets.cr
  src/placeos-rest-api/controllers/authentications.cr
  src/placeos-rest-api/controllers/brokers.cr
  src/placeos-rest-api/controllers/domains.cr
  src/placeos-rest-api/controllers/drivers.cr
  src/placeos-rest-api/controllers/edges.cr
  src/placeos-rest-api/controllers/metadata.cr
  src/placeos-rest-api/controllers/modules.cr
  src/placeos-rest-api/controllers/oauth_applications.cr
  src/placeos-rest-api/controllers/repositories.cr
  src/placeos-rest-api/controllers/schema.cr
  src/placeos-rest-api/controllers/settings.cr
  src/placeos-rest-api/controllers/system-triggers.cr
  src/placeos-rest-api/controllers/systems.cr
  src/placeos-rest-api/controllers/triggers.cr
  src/placeos-rest-api/controllers/users.cr
  src/placeos-rest-api/controllers/zones.cr
Labels: type: refactor

#261 feat: add driver response codes to public API
  shard.lock
  src/placeos-rest-api/utilities/responders.cr
  src/placeos-rest-api/websocket/session.cr
  src/placeos-rest-api/websocket/session/response.cr
Labels: focus: backend, product: placeos, priority: high, type: enhancement
