Repository PlaceOS/rest-api, pull requests merged in 2022-05, with the labels that each got.

#269 feat(metadata): PATCH to patch `details`, PUT to replace
  shard.lock
  src/placeos-rest-api/controllers/metadata.cr
Labels: type: enhancement

#270 fix(controller/edges): include `x_api_token` in Edge creation response
  shard.lock
  spec/controllers/edges_spec.cr
  src/placeos-rest-api/controllers/edges.cr
Labels: type: bug

#271 feat(controller/metadata): add pagination for `query` route
  shard.lock
  src/placeos-rest-api/controllers/application.cr
  src/placeos-rest-api/controllers/metadata.cr
Labels: type: enhancement

#273 feat(users): resource token to default to first oauth app
  src/placeos-rest-api/controllers/users.cr
Labels: focus: backend, product: placeos, priority: high, squad: core, type: enhancement

#274 chore: bump frontend-loader client
  shard.lock
  shard.yml
Labels: type: chore

#275 feat(repositories): new method for repository pull feedback
  shard.lock
  src/placeos-rest-api/controllers/repositories.cr
Labels: type: enhancement

#276 chore(shard.lock): bump deps
  shard.lock
Labels: type: chore

#277 fix(repositories): inconsistent pull responses
  src/placeos-rest-api/controllers/repositories.cr
Labels: type: bug

#278 test(edge): authentication of edge client with the API
  docker-compose.yml
  shard.lock
  shard.yml
  spec/controllers/edges_spec.cr
  src/placeos-rest-api/controllers/edges.cr
Labels: type: bug
