Repository PlaceOS/rest-api, pull requests merged in 2022-02, with the labels that each got.

#229 chore: bump models
  shard.lock
  shard.yml
  spec/controllers/settings_spec.cr
  src/constants.cr
Labels: type: maintenance

#230 test(settings): stricter spec to avoid exception
  spec/controllers/settings_spec.cr
Labels: type: bug

#232 ci: centralised build dev img
  .github/workflows/build-dev-image.yml
  .github/workflows/build.yml
  README.md
Labels: focus: devops, type: refactor

#231 test(all): run pending spec
  docker-compose.yml
  shard.lock
  spec/controllers/drivers_spec.cr
  spec/controllers/systems_spec.cr
  spec/core_helper.cr
  spec/helper.cr
  spec/http_mocks.cr
  spec/websocket/session_spec.cr
  src/placeos-rest-api/controllers/drivers.cr
Labels: type: enhancement

#234 feat(root): add additional logging to signal requests
  src/placeos-rest-api/controllers/root.cr
Labels: focus: backend, product: placeos, priority: low

#235 refactor(edge): ApiKey for edge token
  .github/workflows/changelog.yml
  .github/workflows/validate-pr.yml
  CHANGELOG.md
  shard.lock
  shard.yml
  spec/controllers/api_key_spec.cr
  spec/controllers/asset_instances_spec.cr
  spec/controllers/asset_spec.cr
  spec/controllers/brokers_spec.cr
  spec/controllers/drivers_spec.cr
  spec/controllers/edges_spec.cr
  spec/controllers/modules_spec.cr
  spec/controllers/repositories_spec.cr
  spec/controllers/settings_spec.cr
  spec/controllers/system-triggers_spec.cr
  spec/controllers/systems_spec.cr
  spec/controllers/triggers_spec.cr
  spec/controllers/users_spec.cr
  spec/controllers/zones_spec.cr
  spec/helper.cr
  spec/scope_helper.cr
  src/placeos-rest-api/controllers/api_keys.cr
  src/placeos-rest-api/controllers/application.cr
  src/placeos-rest-api/controllers/edges.cr
  src/placeos-rest-api/controllers/edges/connection_manager.cr
  src/placeos-rest-api/controllers/webhook.cr
  src/placeos-rest-api/controllers/zones.cr
  src/placeos-rest-api/utilities/scopes.cr
  src/placeos-rest-api/websocket/session.cr
Labels: type: bug, type: refactor

#236 fix(root): expose `/platform`
  .github/workflows/ci.yml
  src/placeos-rest-api/controllers/root.cr
Labels: type: bug
